spring:
  application:
    name: weshopify-authn-service
  datasource:
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    url: jdbc:${DB_TYPE:mysql}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:shopifyme-customers}
    username: ${DB_USER_NAME:root} 
    password: ${DB_USER_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: 13.214.221.98
    port: 6379
    
server:
  port: 5002
  
eureka: 
 instance: 
    preferIpAddress: true      